---
services: docker

before_install:
  # Upgrade Docker.
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

script:
  # Test building Dockerfile.
  - docker build -t local-tor-server .

  ## Test running the container with commands from the Readme

  - echo "*** Run a Tor relay server with defaults and a randomized Nickname ***"
  - docker run -d --init --name=tor-server_relay_1 --net=host -p 9001:9001 --restart=always local-tor-server
  - sleep 30
  - docker logs tor-server_relay_1
  - docker stop tor-server_relay_1
  - docker rm tor-server_relay_1

  - echo "*** Run a Tor relay server with a set Nickname and a Contact-Email ***"
  - docker run -d --init --name=tor-server_relay_1 --net=host -p 9001:9001 -e TOR_NICKNAME=Tor4docker -e CONTACT_EMAIL=tor4@example.org --restart=always local-tor-server
  - sleep 30
  - docker logs tor-server_relay_1
  - docker cp tor-server_relay_1:/var/lib/tor/keys/secret_id_key ./
  - docker cp tor-server_relay_1:/var/lib/tor/keys/ed25519_master_id_secret_key ./
  - cat secret_id_key
  - docker stop tor-server_relay_1
  - docker rm tor-server_relay_1

  - echo "*** Mount customized torrc and the identity keys from a previous Tor relay server installation ***"
  - docker run -d --init --name=tor-server_relay_1 --net=host -p 9001:9001 -p 9030:9030 -v $PWD/tests/torrc:/etc/tor/torrc -v $PWD/tests/data/keys/secret_id_key:/var/lib/tor/keys/secret_id_key -v $PWD/tests/data/keys/ed25519_master_id_secret_key:/var/lib/tor/ed25519_master_id_secret_key --restart=always local-tor-server
  - sleep 30
  - docker logs tor-server_relay_1
  - docker stop tor-server_relay_1
  - docker rm tor-server_relay_1

  - echo "Run a Tor relay server with docker-compose with locally built image"
  - docker-compose --version
  - cd tests
  - docker-compose up -d
  - sleep 60
  - docker-compose logs
  - docker-compose exec -T relay cat /var/lib/tor/fingerprint
