---
services: docker

before_install:
  # Upgrade Docker.
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

script:
  # Test building Dockerfile.
  - docker build -t local-tor-server .

  # Test running the container.
  - docker run -d --init --name=tor_relay_1 -p 9001:9001 --restart=always local-tor-server
  - sleep 60
  - docker logs tor_relay_1

  # Also test docker-compose file
  # ...
